# Generated by Django 4.1.5 on 2023-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('order', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='s_email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='s_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
