# Generated by Django 4.1.5 on 2023-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='city',
            field=models.CharField(default='trivandrum', max_length=100),
        ),
    ]
