# Generated by Django 4.1.5 on 2023-05-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_s_loc_shop_s_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='s_loc',
        ),
        migrations.AddField(
            model_name='order',
            name='loc',
            field=models.CharField(default='trivandrum', max_length=100),
        ),
    ]
