# Generated by Django 4.1.5 on 2023-05-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_s_loc_order_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='loc',
            new_name='s_loc',
        ),
    ]
