# Generated by Django 4.1.5 on 2023-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vegetable_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(default='a@gmail', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
