# Generated by Django 4.1.5 on 2023-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_offer_address_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
