# Generated by Django 4.1.5 on 2023-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_offer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
