# Generated by Django 4.1.5 on 2023-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.EmailField(default='a@gmail', max_length=254),
        ),
    ]
